# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoModule', '0002_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deleted_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
