# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoModule', '0005_todolist_sub_task_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='due_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=None),
        ),
    ]
