# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoModule', '0006_auto_20180813_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['due_date', 'due_time']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deleted_on',
            field=models.DateField(default=None, null=True),
        ),
    ]
